// Dan Ortiz - 05/27/2017
// Project Euler - Problem 2 - Even Fibonacci Numbers
//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#include <iostream>


using namespace std;

int Fib(int, int);

const int a = 4000000;

int main(){
	cout << Fib(1, 1);
	return 0;
}

int Fib(int num, int fib){
	if(num < a && (num % 2 == 0)){
		return num + Fib(num + fib, num);
	}else if (num < a){
		return Fib(num + fib, num);
	}else{
		return 0;
	}
}
